### ISSUE TITLE
Playbook sample please

### ISSUE THREAD

**Issue by uridicaprio** [jdchaiken/solarwinds-Node_Module#2]
Hi jdchaiken,

I am having trouble working out how to use your module. 

Would you do me a favour and upload a playbook sample file or maybe email me at urieder@hotmail.com?

Thanks a lot!

**Comment by jdchaiken** [comment]
I'll find something when I return to the office.  What have you tried?

**Comment by uridicaprio** [comment]
of course it's new years eve! lol    i'm in brazil ... went to work earlier.. now just waiting for the drinking to start :D 

I'm actually new to ansible but an doing well at official modules as they come with a help section... I'm also learning a bit of python so I attempted to read your code and was quite impressed... now i feel like i'll be able to develop further what you have started... once i get the hang of ansible + python. 

I have tried lots of different ansible command lines in the hope that i would be able to work out the errors but no luck.

Anyway you enjoy new years eve and hopefully we'll get to exchange some experiences in this IT World!

Cheers buddy!

**Comment by jdchaiken** [comment]
I just looked through my playbooks, and realized that I dont have one that I can share.  

I'd be happy to help where I can.  What are you trying.  I know for certain that adding and removing ICMP nodes works.  I'm pretty sure I've added SNMP as well.

Can you share what you're trying?

**Comment by Macleykun** [comment]
> I just looked through my playbooks, and realized that I dont have one that I can share.
> 
> I'd be happy to help where I can. What are you trying. I know for certain that adding and removing ICMP nodes works. I'm pretty sure I've added SNMP as well.
> 
> Can you share what you're trying?

sorry to hijack this issue, but while i did find an nice example in the python code, i fail to find the methode to install and use this module sadly.

```bash
ERROR! couldn't resolve module/action 'orion_node'. This often indicates a misspelling, missing collection, or incorrect module path.
```

Example:
```yaml
    - name: solarwinds?
      orion_node:
        orion_hostname: "{{solarwinds_host}}"
        orion_username: "{{solarwinds_username}}"
        orion_password: "{{solarwinds_password}}"
        name: "{{inventory_hostname}}"
        state: muted
        unmanage_from: "2020-03-13T20:58:22.033"
        unmanage_until: "2020-03-14T20:58:22.033"
      delegate_to: localhost
```

Did try to place the python file here:
~/.ansible/plugins/modules/solarwinds.py (0644)

ansible-doc solarwinds
does resolve and output the options your module brings!

**Comment by Macleykun** [comment]
Read a bit futher on this, so i now have: "orionsdk required for this module"
i'll have a deeper look myself first how to get that module in my playbook folder

I solved my previous one by installing it like so:
(create a directory called library where your playbooks are)
`wget "https://raw.githubusercontent.com/jdchaiken/solarwinds-Node_Module/master/orion_node.py" -O ./library/solarwinds.py`

**Comment by Macleykun** [comment]
Almost getting there! So to fix  the pip issue it's best to use this task beforehand:
```yaml
    - name: Install needed orionsdk pip package
      pip:
        name: orionsdk
        executable: pip3
        state: present
      delegate_to: localhost
```
The only problem i'm now facing is that i need to set a custom port, but can't find out how

**Comment by Macleykun** [comment]
Finnaly got it to work, if someone ever stumbles across this. Here's how you can use this module in ansible yourself!

It's assumed you want to keep this modulair.

```bash
cd myplaybookSWfolder/
mkdir library/
wget "https://raw.githubusercontent.com/jdchaiken/solarwinds-Node_Module/master/orion_node.py" -O ./library/solarwinds.py
```

The playbook tasks should look like this:

```yaml
    - name: Install needed orionsdk and python-dateutil pip3 packages
      pip:
        name:
          - orionsdk
          - python-dateutil
        executable: pip3
        state: present
        extra_args: --user
      #delegate_to: youcanspecifyanhostoripifneeded
      vars:
        ansible_python_interpreter: /usr/bin/python3

#    - name: Change port through the sdk in an truely awful way, yes i've should've used the lininfile module!
#      ansible.builtin.shell:
#        cmd: sed -i 's/17778/17774/g' ~/.local/lib/python3.6/site-packages/orionsdk/swisclient.py
      #delegate_to: youcanspecifyanhostoripifneeded

    - name: solarwinds?
      solarwinds:
        orion_hostname: "{{solarwinds_host}}"
        orion_username: "{{solarwinds_username}}"
        orion_password: "{{solarwinds_password}}"
        name: "yourhostobjectIDorIPorName"
        state: remanaged/unmanaged/mute/unmute
      #delegate_to: youcanspecifyanhostoripifneeded
      vars:
        ansible_python_interpreter: /usr/bin/python3
```

Note that i specified the interpreter b/c the host still has python2 on it.
The delegate_to was needed b/c you shouldn't want to have every server have api access to your SW instance.
The library part is needed b/c this is where ansible will look for you into.
Tested with both ansible-playbook and ansible-navigator.

If you want to see what options you can use:

```
options:
    orion_hostname:
        description:
            - Name of Orion host running SWIS service
        required: true
    orion_username:
        description:
            - Orion Username
            - Active Directory users may use DOMAIN\\username or username@DOMAIN format
        required: true
    orion_password:
        description:
            - Password for Orion user
        required: true
    state:
        description:
            - The desired state of the node
        required: false
        choices:
            - present
            - absent
            - remanaged
            - unmanaged
            - muted
            - unmuted
        default:
            - remanaged
    node_id:
        description:
            - node_id of the node
            - Must provide either an IP address, node_id, or exact node name
        required: false
    name:
        description:
            - Hostname of the node
            - For Adding a node this field is required
            - For All other states field is optional and partial names are acceptable
        required: false
    ip_address:
        description:
            - IP Address of the node
            - Must provide either an IP address, node_id, or exact node name
        required: false
    unmanage_from:
        description:
            - "The date and time (in ISO 8601 UTC format) to begin the unmanage period."
            - If this is in the past, the node will be unmanaged effective immediately.
            - If not provided, module defaults to now.
            - "ex: 2017-02-21T12:00:00Z"
        required: false
    unmanage_until:
        description:
            - "The date and time (in ISO 8601 UTC format) to end the unmanage period."
            - You can set this as far in the future as you like.
            - If not provided, module defaults to 24 hours from now.
            - "ex: 2017-02-21T12:00:00Z"
        required: false
    polling_method:
        description:
            - Polling method to use
        choices:
            - External
            - icmp
            - snmp
            - WMI
            - agent
            - vcenter
            - meraki
        default: snmp
        required: false
    polling_engine_name:
        description:
            - Name of polling engine that NPM will use to poll this device
        required: false
        type: str
    polling_engine_id:
        description:
            - ID of polling engine that NPM will use to poll this device
        required: false
        type: int
    snmp_version:
        description:
            - SNMPv2c is used by default
            - SNMPv3 requires use of existing, named SNMPv3 credentials within Orion
        choices:
            - 2
            - 3
        default: 2
        required: false
        type: int
    snmp_port:
        description:
            - port that SNMP server listens on
        required: false
        default: 161
        type: int
    snmp_allow_64:
        description:
            - Set true if device supports 64-bit counters
        type: bool
        default: true
        required: false
    credential_name:
        description:
            - The named, existing credential to use to manage this device
        required: true
        type: str
    interface_filters:
        description:
            - List of SolarWinds Orion interface discovery filters
        required: false
        type: list
    volume_filters:
        description:
            - List of regular expressions by which to exclude volumes from monitoring
        required: false
        type: list
    custom_properties:
        description:
            - A dictionary containing custom properties and their values
        required: false
        type: dict
```

Thanks for your work @uridicaprio. Hope this message will make it over to you :)
