### ISSUE TITLE
New-style module did not handle its own exit

### ISSUE THREAD

**Issue by UnknownGnome** [jdchaiken/solarwinds-Node_Module#3]
When running your sweet module, I'm getting this error:

```
{
    "msg": "New-style module did not handle its own exit",
    "_ansible_no_log": false,
    "changed": false,
    "_ansible_delegated_vars": {
        "ansible_host": "localhost"
    }
}
```

Ansible version 2.9.3
I added the file to library.
playbook.yml
```
---
- name: Mute hosts
  hosts: platform_windows
  gather_facts: no
  tasks: 
    - orion_node:
        hostname: "{{solarwinds_host}}"
        username: "{{solarwinds_username}}"
        password: "{{solarwinds_password}}"
        name: "{{inventory_hostname}}"
        state: muted
      delegate_to: localhost
```

I'd love to get this working, but I'm not sure how to proceed from here.
